# Generated by Django 4.2.17 on 2024-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="type",
            field=models.CharField(default="", max_length=128),
        ),
    ]
